repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'main']
    - id: check-added-large-files
    - id: check-merge-conflict
- repo: local
  hooks:
    - id: xilinx-regression
      name: xilinx-regression
      entry: ./script/regression.sh
      language: script
      pass_filenames: false
      stages: ['pre-push']
